# Generated by Django 5.0.6 on 2024-06-27 17:36

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyjournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='activity_strength',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='good_things',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='reflections',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='journal',
            name='sleep_time',
            field=models.FloatField(),
        ),
    ]
