# Generated by Django 5.0.6 on 2024-05-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weather", name="data", field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="weather",
            name="measurement_time",
            field=models.TextField(default="15:47"),
        ),
        migrations.AlterField(
            model_name="weather",
            name="name",
            field=models.CharField(default="Odczyt z dnia 2024-05-13", max_length=200),
        ),
        migrations.AlterField(
            model_name="weather",
            name="rainfall",
            field=models.FloatField(verbose_name="Opad deszczu"),
        ),
    ]
