# Generated by Django 5.0.6 on 2024-05-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather_data_alter_weather_measurement_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='weather',
            name='measurement_time',
            field=models.TextField(default='17:41'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='name',
            field=models.CharField(default='Odczyt z dnia 2024-05-19', max_length=200),
        ),
    ]
