# Generated by Django 5.0.6 on 2024-06-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weather_measurement_time_alter_weather_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='measurement_time',
            field=models.TextField(default='16:58'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='name',
            field=models.CharField(default='Odczyt z dnia 2024-06-25', max_length=200),
        ),
        migrations.AlterField(
            model_name='weather',
            name='summary',
            field=models.TextField(blank=True, help_text='Tekst zwrotny z chatGPT, domyślnie pusty', null=True, verbose_name='Podsumowanie pogody OpenAI'),
        ),
    ]
